### ISSUE TITLE
Installing on OS X - linking issue

### ISSUE THREAD

**Issue by gdtroszak** [TeamShadow/shadow#10]
I've managed to install the shadow compiler on OS X using the Linux instructions. However, when I try to compile the "Hello, World!" tutorial `shadowc HelloWorld.shadow` I get the following error;

```
FILE DEPENDENCY ERROR: Cannot run program "llvm-link": error=2, No such file or directory
java.io.IOException: Cannot run program "llvm-link": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
    at shadow.Main.run(Main.java:370)
    at shadow.Main.main(Main.java:70)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:185)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
    ... 2 more
```

I think that OS X provides a version of llvm through XCode. Here are the details of `llvm-gcc -v`;

```
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

`which llvm-link` yields nothing though. I know OS X provides other linkers...

Any thoughts? Any additional info that I can provide that may help? Note that `shadowc -n HelloWorld.shadow` and `shadowc -t HelloWorld.shadow` both work.

**Comment by Brinsky** [comment]
Interesting post related to Clang assembler problems:
http://stackoverflow.com/questions/11118887/how-to-switch-off-llvms-integrated-assembler
