### ISSUE TITLE
Crash when a literal String is broken by a newline

### ISSUE THREAD

**Issue by Brinsky** [TeamShadow/shadow#27]
The following code produces a compiler crash:
```
class Test
{
        public main(String[] args) => ()
        {
                String broken = "This string
                                isn't valid";
        }
}
```
The crash in question is as follows:
```
Exception in thread "main" shadow.parser.javacc.TokenMgrError: Lexical error at line 5, column 45.  Encountered: "\n" (10), after : "\"This string"
        at shadow.parser.javacc.ShadowParserTokenManager.getNextToken(ShadowParserTokenManager.java:2163)
        at shadow.parser.javacc.ShadowParser.jj_scan_token(ShadowParser.java:9978)
        at shadow.parser.javacc.ShadowParser.jj_3R_348(ShadowParser.java:8471)
        at shadow.parser.javacc.ShadowParser.jj_3R_344(ShadowParser.java:8479)
        at shadow.parser.javacc.ShadowParser.jj_3R_342(ShadowParser.java:8528)
        at shadow.parser.javacc.ShadowParser.jj_3R_341(ShadowParser.java:8559)
        at shadow.parser.javacc.ShadowParser.jj_3R_340(ShadowParser.java:8606)
        at shadow.parser.javacc.ShadowParser.jj_3R_334(ShadowParser.java:8678)
        at shadow.parser.javacc.ShadowParser.jj_3R_329(ShadowParser.java:8694)
        at shadow.parser.javacc.ShadowParser.jj_3R_317(ShadowParser.java:8748)
        at shadow.parser.javacc.ShadowParser.jj_3R_307(ShadowParser.java:8770)
        at shadow.parser.javacc.ShadowParser.jj_3R_292(ShadowParser.java:8790)
        at shadow.parser.javacc.ShadowParser.jj_3R_261(ShadowParser.java:8806)
        at shadow.parser.javacc.ShadowParser.jj_3R_239(ShadowParser.java:8816)
        at shadow.parser.javacc.ShadowParser.jj_3R_210(ShadowParser.java:8832)
        at shadow.parser.javacc.ShadowParser.jj_3R_193(ShadowParser.java:8848)
        at shadow.parser.javacc.ShadowParser.jj_3R_175(ShadowParser.java:8866)
        at shadow.parser.javacc.ShadowParser.jj_3R_154(ShadowParser.java:8876)
        at shadow.parser.javacc.ShadowParser.jj_3R_112(ShadowParser.java:8886)
        at shadow.parser.javacc.ShadowParser.jj_3R_75(ShadowParser.java:8896)
        at shadow.parser.javacc.ShadowParser.jj_3R_153(ShadowParser.java:7211)
        at shadow.parser.javacc.ShadowParser.jj_3R_109(ShadowParser.java:7375)
        at shadow.parser.javacc.ShadowParser.jj_3R_105(ShadowParser.java:9730)
        at shadow.parser.javacc.ShadowParser.jj_3R_141(ShadowParser.java:9783)
        at shadow.parser.javacc.ShadowParser.jj_3R_101(ShadowParser.java:9818)
        at shadow.parser.javacc.ShadowParser.jj_3_42(ShadowParser.java:9824)
        at shadow.parser.javacc.ShadowParser.jj_2_42(ShadowParser.java:7085)
        at shadow.parser.javacc.ShadowParser.BlockStatement(ShadowParser.java:5440)
        at shadow.parser.javacc.ShadowParser.Block(ShadowParser.java:5407)
        at shadow.parser.javacc.ShadowParser.MethodDeclaration(ShadowParser.java:1447)
        at shadow.parser.javacc.ShadowParser.ClassOrInterfaceBodyDeclaration(ShadowParser.java:956)
        at shadow.parser.javacc.ShadowParser.ClassOrInterfaceBody(ShadowParser.java:898)
        at shadow.parser.javacc.ShadowParser.ClassOrInterfaceDeclaration(ShadowParser.java:385)
        at shadow.parser.javacc.ShadowParser.CompilationUnit(ShadowParser.java:64)
        at shadow.typecheck.TypeCollector.collectTypes(TypeCollector.java:142)
        at shadow.typecheck.TypeChecker.typeCheck(TypeChecker.java:43)
        at shadow.Main.generateLLVM(Main.java:228)
        at shadow.Main.run(Main.java:138)
        at shadow.Main.main(Main.java:68)
```

**Comment by bwittman** [comment]
As of commit 57ae11575054f165549de1e8693207695c8e7633, an appropriate error message should be given instead of crashing the parser.
