### ISSUE TITLE
Crash when trying to implement linked lists

### ISSUE THREAD

**Issue by schubertr** [TeamShadow/shadow#30]
I was fooling around and just trying to implement a very basic linked list class. As I was going through fixing things, the compiler seemed to crash. The first bit of code is my test class with my main method, the second is my linked list class, and the third is the output. The crash seems to be happening at the last three lines of the add() method in the list class.

Main:

    import shadow:io@Console;
    
    class mainCode
    {
    	public main( String[] args ) => ()
    	{
    		numList = list.newList();
    		numList.addHead(2);
    		numList.add(0);
    		numList.add(1);
    		numList.add(5);
    		
    		numList.print();
    	}
    
    }

Linked List:
    
    import shadow:io@Console;
    
    class list
    {
        private class Node
        {
            int value;
            Node next;
        }
        
        Node head;
        int size = 0;
        
        public newList() => (list)
        {
            head = null;
            return head;
        }
        
        public isEmpty() => (boolean)
        {
            return head != null;
        }
        
        public addHead(int num) => ()
        {
            head = Node();
            head.value = num;
            size = size + 1;
        }
        
        public add(int num) => ()
        {
            if(isEmpty())
            addHead(num);
            else
            {
                Node temp = Node();
                Node cur = head;
                
                while(cur.next != null)
                cur = cur.next;
                
                cur.next = Node();
                cur.next.value = num;
                size = size + 1;
            }
        }
        
        public clear() => ()
        {
            head = null;
        }
        
        public print() => ()
        {
            Console out;
            
            if(isEmpty())
            out.printLine("List is empty");
            else
            {
                
                int i = 1;
                Node cur = head;
                
                while(cur.next != null)
                {
                    out.printLine("Node # i # ": " # cur.value);
                    i += 1;
                }
                
            }
            
        }
    }

Output:

    Ryans-MacBook-Pro:linked-list Ryan$ shadowc mainCode.shadow
    Exception in thread "main" shadow.parser.javacc.TokenMgrError: Lexical error at line 69, column 61.  Encountered: "\r" (13), after : "\" # cur.value);"
    	at shadow.parser.javacc.ShadowParserTokenManager.getNextToken(ShadowParserTokenManager.java:2163)
    	at shadow.parser.javacc.ShadowParser.jj_scan_token(ShadowParser.java:9978)
    	at shadow.parser.javacc.ShadowParser.jj_3R_128(ShadowParser.java:7911)
    	at shadow.parser.javacc.ShadowParser.jj_3R_90(ShadowParser.java:7934)
    	at shadow.parser.javacc.ShadowParser.jj_3_29(ShadowParser.java:8047)
    	at shadow.parser.javacc.ShadowParser.jj_3R_87(ShadowParser.java:8018)
    	at shadow.parser.javacc.ShadowParser.jj_3R_200(ShadowParser.java:8353)
    	at shadow.parser.javacc.ShadowParser.jj_3R_184(ShadowParser.java:8382)
    	at shadow.parser.javacc.ShadowParser.jj_3R_353(ShadowParser.java:8443)
    	at shadow.parser.javacc.ShadowParser.jj_3R_344(ShadowParser.java:8489)
    	at shadow.parser.javacc.ShadowParser.jj_3R_342(ShadowParser.java:8528)
    	at shadow.parser.javacc.ShadowParser.jj_3R_341(ShadowParser.java:8559)
    	at shadow.parser.javacc.ShadowParser.jj_3R_340(ShadowParser.java:8606)
    	at shadow.parser.javacc.ShadowParser.jj_3R_334(ShadowParser.java:8678)
    	at shadow.parser.javacc.ShadowParser.jj_3R_329(ShadowParser.java:8694)
    	at shadow.parser.javacc.ShadowParser.jj_3R_317(ShadowParser.java:8748)
    	at shadow.parser.javacc.ShadowParser.jj_3R_307(ShadowParser.java:8770)
    	at shadow.parser.javacc.ShadowParser.jj_3R_292(ShadowParser.java:8790)
    	at shadow.parser.javacc.ShadowParser.jj_3R_261(ShadowParser.java:8806)
    	at shadow.parser.javacc.ShadowParser.jj_3R_239(ShadowParser.java:8816)
    	at shadow.parser.javacc.ShadowParser.jj_3R_210(ShadowParser.java:8832)
    	at shadow.parser.javacc.ShadowParser.jj_3R_193(ShadowParser.java:8848)
    	at shadow.parser.javacc.ShadowParser.jj_3R_175(ShadowParser.java:8866)
    	at shadow.parser.javacc.ShadowParser.jj_3R_154(ShadowParser.java:8876)
    	at shadow.parser.javacc.ShadowParser.jj_3R_112(ShadowParser.java:8886)
    	at shadow.parser.javacc.ShadowParser.jj_3R_75(ShadowParser.java:8896)
    	at shadow.parser.javacc.ShadowParser.jj_3R_178(ShadowParser.java:7479)
    	at shadow.parser.javacc.ShadowParser.jj_3R_162(ShadowParser.java:7626)
    	at shadow.parser.javacc.ShadowParser.jj_3R_124(ShadowParser.java:7965)
    	at shadow.parser.javacc.ShadowParser.jj_3R_87(ShadowParser.java:8034)
    	at shadow.parser.javacc.ShadowParser.jj_3R_200(ShadowParser.java:8353)
    	at shadow.parser.javacc.ShadowParser.jj_3R_184(ShadowParser.java:8382)
    	at shadow.parser.javacc.ShadowParser.jj_3R_353(ShadowParser.java:8443)
    	at shadow.parser.javacc.ShadowParser.jj_3R_344(ShadowParser.java:8489)
    	at shadow.parser.javacc.ShadowParser.jj_3R_342(ShadowParser.java:8528)
    	at shadow.parser.javacc.ShadowParser.jj_3R_341(ShadowParser.java:8559)
    	at shadow.parser.javacc.ShadowParser.jj_3R_340(ShadowParser.java:8606)
    	at shadow.parser.javacc.ShadowParser.jj_3R_334(ShadowParser.java:8678)
    	at shadow.parser.javacc.ShadowParser.jj_3R_329(ShadowParser.java:8694)
    	at shadow.parser.javacc.ShadowParser.jj_3R_317(ShadowParser.java:8748)
    	at shadow.parser.javacc.ShadowParser.jj_3R_307(ShadowParser.java:8770)
    	at shadow.parser.javacc.ShadowParser.jj_3R_292(ShadowParser.java:8790)
    	at shadow.parser.javacc.ShadowParser.jj_3R_261(ShadowParser.java:8806)
    	at shadow.parser.javacc.ShadowParser.jj_3R_239(ShadowParser.java:8816)
    	at shadow.parser.javacc.ShadowParser.jj_3R_210(ShadowParser.java:8832)
    	at shadow.parser.javacc.ShadowParser.jj_3R_193(ShadowParser.java:8848)
    	at shadow.parser.javacc.ShadowParser.jj_3R_175(ShadowParser.java:8866)
    	at shadow.parser.javacc.ShadowParser.jj_3R_154(ShadowParser.java:8876)
    	at shadow.parser.javacc.ShadowParser.jj_3R_112(ShadowParser.java:8886)
    	at shadow.parser.javacc.ShadowParser.jj_3R_75(ShadowParser.java:8896)
    	at shadow.parser.javacc.ShadowParser.jj_3R_111(ShadowParser.java:7284)
    	at shadow.parser.javacc.ShadowParser.jj_3R_74(ShadowParser.java:7366)
    	at shadow.parser.javacc.ShadowParser.jj_3R_221(ShadowParser.java:8093)
    	at shadow.parser.javacc.ShadowParser.jj_3R_199(ShadowParser.java:8160)
    	at shadow.parser.javacc.ShadowParser.jj_3R_184(ShadowParser.java:8378)
    	at shadow.parser.javacc.ShadowParser.jj_3R_165(ShadowParser.java:9650)
    	at shadow.parser.javacc.ShadowParser.jj_3R_139(ShadowParser.java:9674)
    	at shadow.parser.javacc.ShadowParser.jj_3R_100(ShadowParser.java:9688)
    	at shadow.parser.javacc.ShadowParser.jj_3_41(ShadowParser.java:7179)
    	at shadow.parser.javacc.ShadowParser.jj_2_41(ShadowParser.java:7078)
    	at shadow.parser.javacc.ShadowParser.Statement(ShadowParser.java:5252)
    	at shadow.parser.javacc.ShadowParser.WhileStatement(ShadowParser.java:6039)
    	at shadow.parser.javacc.ShadowParser.Statement(ShadowParser.java:5226)
    	at shadow.parser.javacc.ShadowParser.BlockStatement(ShadowParser.java:5494)
    	at shadow.parser.javacc.ShadowParser.Block(ShadowParser.java:5407)
    	at shadow.parser.javacc.ShadowParser.Statement(ShadowParser.java:5258)
    	at shadow.parser.javacc.ShadowParser.IfStatement(ShadowParser.java:6002)
    	at shadow.parser.javacc.ShadowParser.Statement(ShadowParser.java:5223)
    	at shadow.parser.javacc.ShadowParser.BlockStatement(ShadowParser.java:5494)
    	at shadow.parser.javacc.ShadowParser.Block(ShadowParser.java:5407)
    	at shadow.parser.javacc.ShadowParser.MethodDeclaration(ShadowParser.java:1447)
    	at shadow.parser.javacc.ShadowParser.ClassOrInterfaceBodyDeclaration(ShadowParser.java:956)
    	at shadow.parser.javacc.ShadowParser.ClassOrInterfaceBody(ShadowParser.java:898)
    	at shadow.parser.javacc.ShadowParser.ClassOrInterfaceDeclaration(ShadowParser.java:385)
    	at shadow.parser.javacc.ShadowParser.CompilationUnit(ShadowParser.java:64)
    	at shadow.typecheck.TypeCollector.collectTypes(TypeCollector.java:142)
    	at shadow.typecheck.TypeChecker.typeCheck(TypeChecker.java:43)
    	at shadow.Main.generateLLVM(Main.java:228)
    	at shadow.Main.run(Main.java:138)
    	at shadow.Main.main(Main.java:68)

Any ideas on what is causing this? If so, how can I fix it? Thanks.

**Comment by schubertr** [comment]
Actually it looks like it thinks there's a newline ( \ r ) somewhere in my printLine at the bottom of the list class. There doesn't appear to be one though.

**Comment by Brinsky** [comment]
It looks like that newline error is stemming from a missing quotation mark between `out.printLine("Node ` and `# i # ": " # cur.value);`. The exception being thrown isn't exactly intuitive, but that's a different issue.

There are also a few additional problems with the code above, most of which are understandable when coming from a Java background:
- Setting references to `null` is only possible when their type is declared as `nullable`. For example, `Node head` must a be `nullable Node head` in order to become null at any point. It is also necessary to "check" a nullable reference before accessing its value in non-nullable context, i.e. `Node safe = check(head);` or `int i = check(head)->value;`

- Constructing objects in Shadow requires use of the special `create()` method, so `Node temp = Node()` should be `Node temp = Node:create()`. Even though a default constructor exists, you should take great care to explicitly initialize all data members, as the compiler cannot yet detect uninitialized variables

- Because all class data members must be private, it is not actually possible to access a Node's `value` or `next` fields directly. Even if it were, the field-access operator in Shadow is `:` instead of `.`. To avoid this issue, Shadow provides `get` and `set` properties, which generate handy default methods when applied to a field. For example, `get int value;` would make it possible to access a value through `head->value` or the like

Although a centralized and up-to-date Shadow language reference does not exist, there are a few good places to learn about and check up on these things:
- [The "Features" page on Shadow's website](http://shadow-language.org/features/) (slightly out of date with the latest compiler)
- [The source code for the standard library](https://github.com/TeamShadow/shadow/tree/master/shadow) (provides good, successfully-compiling examples; hopefully always up to date)
- [The commit log](https://github.com/TeamShadow/shadow/commits/master) (may provide brief examples and descriptions of new features)

You may also find the source code of [shadow:utility@LinkedList](https://github.com/TeamShadow/shadow/blob/master/shadow/utility/LinkedList.shadow) to be helpful in this particular case. Interestingly enough, it takes a different approach in which a dummy `header` Node is used in place of null.
